@startuml
'https://plantuml.com/class-diagram

class User {
    + id: Long
    + name: String
    + email: String
    + fun getName()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

enum SignInState {
    SignIn
    SignOut
    Loading
}

class item {
    name: String
    price: Double
}

class User {
    name: String
    email: String
    age: Int
    profileImage: String
    bio: String
}
@enduml